# Generated by Django 5.1 on 2024-09-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_address_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
