# Generated by Django 5.1 on 2024-09-15 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='field',
            new_name='title',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ImageField(null=True, upload_to='banners')),
                ('banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.banner')),
            ],
        ),
    ]
