# Generated by Django 5.1 on 2024-09-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_field_banner_title_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='image',
        ),
    ]
