# Generated by Django 5.1 on 2024-09-15 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0003_image'),
        ('mainapp', '0010_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothesproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothes_categories', to='app_social.category'),
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digital_categories', to='app_social.category'),
        ),
    ]
