# Generated by Django 5.1 on 2024-09-19 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0003_image'),
        ('mainapp', '0011_clothesproduct_category_digitalproduct_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothesproduct',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.brand'),
        ),
        migrations.AddField(
            model_name='clothesproduct',
            name='count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clothesproduct',
            name='images',
            field=models.ManyToManyField(to='app_social.image'),
        ),
        migrations.AddField(
            model_name='clothesproduct',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clothesproduct',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.brand'),
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='images',
            field=models.ManyToManyField(to='app_social.image'),
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
