# Generated by Django 5.1 on 2024-09-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_clothesproduct_brand_clothesproduct_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothesproduct',
            name='images',
        ),
        migrations.RemoveField(
            model_name='digitalproduct',
            name='images',
        ),
    ]
