# Generated by Django 5.1 on 2024-09-21 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mainapp', '0013_remove_clothesproduct_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='banner',
        ),
        migrations.AddField(
            model_name='image',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_store_images', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='image',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
