# Generated by Django 5.1 on 2024-09-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_image_banner_image_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='clothesproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='digitalproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='clothesproduct',
            name='category',
            field=models.ManyToManyField(to='mainapp.category'),
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='category',
            field=models.ManyToManyField(to='mainapp.category'),
        ),
    ]
