# Generated by Django 5.1 on 2024-09-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_category_remove_clothesproduct_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='field',
            new_name='color',
        ),
    ]
