# Generated by Django 5.1 on 2024-09-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_rename_field_color_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
        migrations.AddField(
            model_name='clothesproduct',
            name='color',
            field=models.ManyToManyField(to='mainapp.color'),
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='color',
            field=models.ManyToManyField(to='mainapp.color'),
        ),
    ]
