# Generated by Django 5.1 on 2024-09-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_clothesproduct_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesproduct',
            name='color',
            field=models.ManyToManyField(to='mainapp.color'),
        ),
    ]
