# Generated by Django 5.1 on 2024-09-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_digitalproduct_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_value',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
