# Generated by Django 5.1 on 2024-10-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0004_alter_basketitem_product_alter_orderitem_product'),
        ('mainapp', '0023_remove_clothesproduct_brand_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClothesProduct',
        ),
        migrations.DeleteModel(
            name='DigitalProduct',
        ),
    ]
