# Generated by Django 5.1 on 2024-10-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_delete_clothesproduct_delete_digitalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_suggested',
            field=models.BooleanField(default=False),
        ),
    ]
