# Generated by Django 5.1 on 2024-09-29 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0001_initial'),
        ('mainapp', '0022_alter_color_hex_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.color'),
        ),
    ]
