# Generated by Django 5.1 on 2024-09-29 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0002_basketitem_color'),
        ('mainapp', '0022_alter_color_hex_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.clothesproduct'),
        ),
    ]
