# Generated by Django 5.1 on 2024-09-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_address_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
