# Generated by Django 5.1 on 2024-09-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_no',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
