# Generated by Django 5.1 on 2024-09-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
    ]
