# Generated by Django 5.1 on 2024-09-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0002_remove_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
