# Generated by Django 5.1 on 2024-09-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='field',
            new_name='name',
        ),
    ]
