# Generated by Django 5.1 on 2024-09-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0005_image_content_type_image_object_id'),
        ('mainapp', '0015_category_remove_clothesproduct_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='store/images/'),
        ),
    ]
